name: Test

on: [push, pull_request]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.201'
    - name: Test
      run: |
        dotnet add "UnitTests" package Microsoft.NET.Test.Sdk
        dotnet add "UnitTests" package GitHubActionsTestLogger
        dotnet add "UnitTests" package coverlet.msbuild
        dotnet test "UnitTests" -c Release -l GitHubActions /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - uses: codecov/codecov-action@v1
      with:
        file: ./UnitTests/coverage.opencover.xml
